[[packages]]
name = "@kaizen/components"
language = "typescript"
folder_paths = ["packages/components/src"]
context_files = "packages/components/.enchiridion/context.md"
structure_context_files = "packages/components/.enchiridion/structure-context.md"

[[packages]]
name = "@kaizen/design-tokens"
language = "typescript"
folder_paths = ["packages/design-tokens/src"]
context_files = "packages/design-tokens/.enchiridion/context.md"
structure_context_files = "packages/design-tokens/.enchiridion/structure-context.md"

[[packages]]
name = "@kaizen/tailwind"
language = "typescript"
folder_paths = ["packages/tailwind/src"]
context_files = "packages/tailwind/.enchiridion/context.md"
structure_context_files = "packages/tailwind/.enchiridion/structure-context.md"
