name: ci

on: push

jobs:
  typescript:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: "14.15.1"
      - name: Install package dependencies
        env:
          PACKAGE_REGISTRY_ACCESS_TOKEN: ${{ secrets.PACKAGE_REGISTRY_ACCESS_TOKEN }}
        run: |
          npm config set "//npm.pkg.github.com/:_authToken" "$PACKAGE_REGISTRY_ACCESS_TOKEN"
          yarn install --frozen-lockfile
      - run: yarn compile

  eslint:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: "14.15.1"
      - name: Install package dependencies
        env:
          PACKAGE_REGISTRY_ACCESS_TOKEN: ${{ secrets.PACKAGE_REGISTRY_ACCESS_TOKEN }}
        run: |
          npm config set "//npm.pkg.github.com/:_authToken" "$PACKAGE_REGISTRY_ACCESS_TOKEN"
          yarn install --frozen-lockfile
      - run: yarn eslint

  prettier:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: "14.15.x"
      - name: Install package dependencies
        env:
          PACKAGE_REGISTRY_ACCESS_TOKEN: ${{ secrets.PACKAGE_REGISTRY_ACCESS_TOKEN }}
        run: |
          npm config set "//npm.pkg.github.com/:_authToken" "$PACKAGE_REGISTRY_ACCESS_TOKEN"
          yarn install --frozen-lockfile
      - run: yarn prettier

  jest-react-16:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: "14.15.x"
      - name: Install package dependencies
        env:
          PACKAGE_REGISTRY_ACCESS_TOKEN: ${{ secrets.PACKAGE_REGISTRY_ACCESS_TOKEN }}
        run: |
          npm config set "//npm.pkg.github.com/:_authToken" "$PACKAGE_REGISTRY_ACCESS_TOKEN"
          yarn install --frozen-lockfile
      - name: Run unit tests
        run: USE_REACT_17=false yarn test --ci

  jest-react-17:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: "14.15.x"
      - name: Install package dependencies
        env:
          PACKAGE_REGISTRY_ACCESS_TOKEN: ${{ secrets.PACKAGE_REGISTRY_ACCESS_TOKEN }}
        run: |
          npm config set "//npm.pkg.github.com/:_authToken" "$PACKAGE_REGISTRY_ACCESS_TOKEN"
          yarn install --frozen-lockfile
      - name: Run unit tests
        run: USE_REACT_17=true yarn test --ci
