name: component-library

on:
  push:
    paths:
      - packages/component-library/**

jobs:
  test-styles-compile:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com/
      - run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn test:pkg:c-library:sass
